#include <iostream>

void hello(std::string name) {
    std::cout << "Hey there " << name << "!, I'm a automated message generated by the system.";
}

int main() {
    std::string name;

    std::cout << "Please enter your name: ";
    std::cin >> name;
    
    hello(name);
}